export const USER_IMPORT_REQUEST = "USER_IMPORT_REQUEST";
export const USER_IMPORT_SUCCESS = "USER_IMPORT_SUCCESS";
export const USER_IMPORT_FAIL = "USER_IMPORT_FAIL";

export const USER_IMPORT_CLEAR_ERRORS = "USER_IMPORT_CLEAR_ERRORS";
