export const EMPLOYEES_REQUEST = "EMPLOYEES_REQUEST";
export const EMPLOYEES_SUCCESS = "EMPLOYEES_SUCCESS";
export const EMPLOYEES_FAIL = "EMPLOYEES_FAIL";
export const EMPLOYEES_CLEAR_ERRORS = "EMPLOYEES_CLEAR_ERRORS";
