export const EMPLOYEES_REQUEST = "EMPLOYEES_REQUEST";
export const EMPLOYEES_SUCCESS = "EMPLOYEES_SUCCESS";
export const EMPLOYEES_FAIL = "EMPLOYEES_FAIL";
export const EMPLOYEES_CLEAR_ERRORS = "EMPLOYEES_CLEAR_ERRORS";


export const UPDATE_EMPLOYEES_REQUEST = "UPDATE_EMPLOYEES_REQUEST";
export const UPDATE_EMPLOYEES_SUCCESS = "UPDATE_EMPLOYEES_SUCCESS";
export const UPDATE_EMPLOYEES_FAIL = "UPDATE_EMPLOYEES_FAIL";
export const UPDATE_EMPLOYEES_CLEAR_ERRORS = "UPDATE_EMPLOYEES_CLEAR_ERRORS";
