export const TEMP_USER_REQUEST = "TEMP_USER_REQUEST";
export const TEMP_USER_SUCCESS = "TEMP_USER_SUCCESS";
export const TEMP_USER_FAIL = "TEMP_USER_FAIL";

export const TEMP_USER_CLEAR_ERRORS = "TEMP_USER_CLEAR_ERRORS";
